project/appointment/urls.py
from django.urls import path
from .views import AppointmentView

urlpatterns = [path('', AppointmentView.as_view(), name='make_appointment')]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('news/', include('simpleapp.urls')),
    path('', include('protect.urls')),
    path('sign/', include('sign.urls')),
    path('accounts/', include('allauth.urls')),
    path('appointment/', include(('appointment.urls', 'appointment'), namespace='appointment'))
]

project/sign/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import BaseRegisterView
from .views import upgrade_me

urlpatterns = [
    path('login/', LoginView.as_view(template_name='sign/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='sign/logout.html'), name='logout'),
    path('signup/', BaseRegisterView.as_view(template_name='sign/signup.html'), name='signup'),

    path('upgrade/', upgrade_me, name='upgrade')
]

project/appointment/models.py
from django.db import models
from datetime import datetime


class Appointment(models.Model):
    client_name = models.CharField(max_length=200)
    message = models.TextField()

    def __str__(self):
        return f'{self.client_name}: {self.message}'

project/simpleapp/models.py
from django.db import models
from django.contrib.auth.models import User


class Author(models.Model):
    name = models.CharField(max_length=255)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    rating = models.IntegerField(default=0)

    def __str__(self):
        return f'{self.name}'

    def update_rating(self):
        query_rating_post = Post.objects.filter(author=self, type="AR").values("rating")
        query_rating_comment = Comment.objects.filter(user=self.user).values("rating")
        query_rating_article = Comment.objects.filter(post__author=self, post__type="AR").values("rating")
        rating_article = 0
        rating_comment = 0
        rating_post = 0
        for qrp in query_rating_post:
            for key, value in qrp.items():
                rating_post += value*3

        for qrc in query_rating_comment:
            for key, value in qrc.items():
                rating_comment += value

        for qra in query_rating_article:
            for key, value in qra.items():
                rating_article += value

        self.rating = rating_post+rating_comment+rating_article
        self.save()


class Category(models.Model):
    name = models.CharField(max_length=255, unique=True)
    subscribers = models.ManyToManyField(User, through='UserCategory')

    def __str__(self):
        return f'{self.name}'


class Post(models.Model):
    news = 'NS'
    article = 'AR'

    TYPE = [
        (news, 'Новость'),
        (article, 'Статья')
    ]
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    type = models.CharField(max_length=2, choices=TYPE, default=news)
    date_posted = models.DateTimeField(auto_now_add=True)
    category = models.ManyToManyField(Category, through='PostCategory')
    title = models.CharField(max_length=255)
    text = models.TextField()
    rating = models.IntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def preview(self):
        return self.text[:125]+'...'

    def get_absolute_url(self): # добавим абсолютный путь чтобы после создания нас перебрасывало на страницу с новостью
        return f'/news/{self.id}'


class PostCategory(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)


class UserCategory(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    date_posted = models.DateTimeField(auto_now_add=True)
    rating = models.IntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

project/appointment/views.py
from django.shortcuts import render, reverse, redirect
from django.template.loader import render_to_string
from django.views import View
from django.core.mail import send_mail, EmailMultiAlternatives
from .models import Appointment


class AppointmentView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'make_appointment.html', {})

    def post(self, request, *args, **kwargs):
        appointment = Appointment(
            client_name=request.POST['client_name'],
            message=request.POST['message'],
        )
        appointment.save()

        # получаем наш html
        html_content = render_to_string(
            'appointment_created.html',
            {
                'appointment': appointment,
            }
        )

        # в конструкторе уже знакомые нам параметры, да? Называются правда немного по другому, но суть та же.
        msg = EmailMultiAlternatives(
            subject=f'{appointment.client_name}',
            body=appointment.message,  # это то же, что и message
            from_email='Christopherga@yandex.ru',
            to=['den.platov.1999@mail.ru', ],  # это то же, что и recipients_list
        )
        msg.attach_alternative(html_content, "text/html")  # добавляем html

        msg.send()  # отсылаем

        return redirect('appointment:make_appointment')

project/templates/appointment.html
<!DOCTYPE html>
<html lang="en">
{% block content %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <p><h4>Здравствуй, {{ appointment.author }} Новая статья в твоём любимом разделе!</h4></p>
    <h2> Название статьи: {{ appointment.title }}</h2><br>
    <h7> {{ appointment.text|truncatechars:50 }}</h7><br><br>
    <h7> Категории:</h7><br><br>
    {%   for name in appointment.category.all %}

    <h7> {{ name.name }}</h7><br>
    {%   endfor  %}<br>
    </li>
            <a href="{{ link }}">Ссылка на статью</a>
    </li><br><br>

    <h7> С уважением, команда NewPortal</h7>
    {% endblock content %}
</body>
</html>

project/templates/appointment_created.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>{{ appointment.client_name }} Спасибо за отзыв!</h2>
    <p> Мы обязательно рассмотрим ваше сообщение! <br>{{ appointment.message|truncatechars:150 }} </p>
</body>
</html>

project/templates/email_confirmation_signup_message.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% load account %} <!-- Загружаем тег который позволит получить нам ссылку на подтверждение -->
    <h1>Thank you for registering {{ user.username }}!</h1>
    <h3>Please follow <a href="{{ activate_url }}">the link</a> to activate your account</h3>
     <!-- Вставляем ссылку на активацию -->
</body>
</html>

project/templates/main.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title> Страница пользователя {{request.user.username}}</title>

        {% load static %}
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Responsive navbar-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
   <div class="container">
       <a class="navbar-brand" href="#">Django flatpages</a>
       <button class="navbar-toggler" type="button" data-toggle="collapse"
               data-target="#navbarResponsive"
               aria-controls="navbarResponsive" aria-expanded="false"
               aria-label="Toggle navigation">
           <span class="navbar-toggler-icon"></span>
       </button>
       <div class="collapse navbar-collapse" id="navbarResponsive">
           <ul class="navbar-nav ml-auto">
               <li class="nav-item">
                   <a class="nav-link" href="/news/">News</a>
               </li>
               <li class="nav-item">
                   <a class="nav-link" href="/about/">About</a>
               </li>
               <li class="nav-item">
                   <a class="nav-link" href="/contacts/">Contact</a>
               </li>
               <li class="nav-item">
                   <a class="nav-link" href="/news/search">Search</a>
               </li>
           </ul>
       </div>
   </div>
</nav>
           <p align="left"><h3><a href="http://127.0.0.1:8000/news/">NewsPortal</a></h3></p>
            <p align="left"><h3><a href="/">SignUp/ SignIn</a></h3></p>
            <p align="left"><h3><a href="http://127.0.0.1:8000/admin">Admin panel</a></h3></p>
    <div class="container">
   <div class="row">
       <div class="col-lg-12 text-center">
           {% block content %}
           {{ flatpage.content }}
           {% endblock content %}
       </div>
   </div>
</div>
    </body>
</html>

project/templates/make_appointment.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Make in record</title>
</head>
<body>
    <h2>Поделитесь своим мнением о сайте:</h2>
<form action="{% url 'appointment:make_appointment' %}" enctype="multipart/form-data" method="POST">
    {% csrf_token %}

    <input type="text" name="client_name" placeholder="Your name..."><br>
    <input type="text" name="message" placeholder="Your feedback..."><br><br>
    <input type="submit">
</form>
</body>
</html>

project/templates/new.html
<!--  наследуемся от шаблона default.html, который мы создавали ещё во времена flatpages -->
{% extends 'flatpages/default.html' %}
{% load custom_filters %}

<!-- Название у нас будет proudcts -->
{% block title %}
News
{% endblock title %}

<!-- В контенте на странице мы выводим сам товар, ID которого было передано в адрес -->
{% block content %}
<div class="brd">
<p align="left"><h3>{{ new.title }} : {{ new.date_posted |date:'d M Y' }}</h3></p>
<p align="left">{{ new.text | filtercen}}</p><p align="left"> <a href="/news/">Вернуться на главную страницу</a> </p>
    {% for c in new.category.all %}
        {% if c in user.category_set.all %}
            <a href="unsubscribe/{{ c.id }}" class="btn btn-danger btn-sm"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-bell" viewBox="0 0 16 16">
      <path d="M8 16a2 2 0 0 0 2-2H6a2 2 0 0 0 2 2zM8 1.918l-.797.161A4.002 4.002 0 0 0 4 6c0 .628-.134 2.197-.459 3.742-.16.767-.376 1.566-.663 2.258h10.244c-.287-.692-.502-1.49-.663-2.258C12.134 8.197 12 6.628 12 6a4.002 4.002 0 0 0-3.203-3.92L8 1.917zM14.22 12c.223.447.481.801.78 1H1c.299-.199.557-.553.78-1C2.68 10.2 3 6.88 3 6c0-2.42 1.72-4.44 4.005-4.901a1 1 0 1 1 1.99 0A5.002 5.002 0 0 1 13 6c0 .88.32 4.2 1.22 6z"/>
    </svg></a>  {{ c.name }}
    {% else %}
            <a href="subscribe/{{ c.id }}" class="btn btn-success btn-sm"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-bell" viewBox="0 0 16 16">
      <path d="M8 16a2 2 0 0 0 2-2H6a2 2 0 0 0 2 2zM8 1.918l-.797.161A4.002 4.002 0 0 0 4 6c0 .628-.134 2.197-.459 3.742-.16.767-.376 1.566-.663 2.258h10.244c-.287-.692-.502-1.49-.663-2.258C12.134 8.197 12 6.628 12 6a4.002 4.002 0 0 0-3.203-3.92L8 1.917zM14.22 12c.223.447.481.801.78 1H1c.299-.199.557-.553.78-1C2.68 10.2 3 6.88 3 6c0-2.42 1.72-4.44 4.005-4.901a1 1 0 1 1 1.99 0A5.002 5.002 0 0 1 13 6c0 .88.32 4.2 1.22 6z"/>
    </svg></a>  {{ c.name }}
    {% endif %}
    {% endfor %}
    </div>
{% endblock content %}

project/templates/news.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %} <!-- не забываем заранее загружать наши фильтры! -->

{% block title %}
News
{% endblock title %}

{% block content %}
    <h1>Лента новостей</h1>
    <hr>
{% for new in news %}
<div class="brd">
<p><h5>{{ new.title }} : {{ new.date_posted |date:'d M Y G:i' }}</h5></p>
<p>{{ new.text|truncatechars:50 | filtercen}}</p><p align="left"><a href="/news/{{new.id}}">Читать далее... </a>
    <p align="left"><a href="/news/update/{{new.id}}">Редактировать </a><a href="/news/delete/{{new.id}}"> Удалить</a>

    </div>
   <hr>
        {% endfor %}

{% if is_paginated %}

    {% if page_obj.has_previous %}
        <a href="?page=1">First</a>
        <a href="?page={{ page_obj.previous_page_number }}"><<<</a>
    {% endif %}

    {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
            <a>{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < obj.number|add:'3' %}
            <a href="?page={{ num }}">{{ num }}</a>
        {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">>>></a>
        <a href="?page={{ page_obj.paginator.num_pages }}">Last</a>
    {% endif %}

{% endif %}
{% endblock content %}

project/templates/news_create.html
{% extends 'flatpages/default.html' %}
{% block title %}
Create
{% endblock title %}

{% block content %}
<h3>Создать/Редактировать</h3>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }} <!-- Теперь нам нужна только готовая форма и кнопка -->
    <input type="submit" value="Добавить товар">
</form>
{% endblock content %}

project/templates/news_delete.html
{% extends 'flatpages/default.html' %}
{% block title %}
Delete
{% endblock title %}

{% block content %}
<h2>Вы действительно хотите удалить данную новость?</h2>
        <div class="brd">
            <p align="left">{{ new.title }}{{new.date_posted|date:'d M Y'}}</p>
            <p align="left">{{ new.text }}</p>
            <p align="left"> <a href="/news/">Назад к списку новостей</a> </p>
        </div>

<form method="POST">
    {% csrf_token %}
    <input type="submit" value="подтвердить"></form>
{% endblock content %}

project/templates/news_detail.html
{% extends 'flatpages/default.html' %}
{% block title %}
News
{% endblock title %}

{% block content %}

{% for obj in filter.qs %}
<h4>{{ obj.title }} : {{ obj.date_posted|date:'d-m-Y h:i'}}</h4><br>
<h6>Автор: {{ obj.author }}<br></h6>

{{ obj.text }}
{% endfor %}

{% endblock content %}

project/templates/search.html
{% extends 'flatpages/default.html' %}
{% block title %}
Search
{% endblock title %}

{% block content %}
<h5>Поиск новостей</h5>

<div class="brd">
<br><form method="GET">
    {{ filter.form }} <!-- Форму от фильтров за нас сделает django. А вот кнопку, увы, придётся делать самому -->
    <input type="submit" value="Найти">
</form>
    </div>
<br>
{% for obj in filter.qs %}
<p align="left"><h4><a href="/news/{{obj.id}}">{{ obj.title }}</a> : {{ obj.date_posted|date:'d-m-Y h:i'}}</h4><br></p>
<p align="left"><h6>Автор: {{ obj.author }}<br></h6></p>
<p align="left">{{ obj.text }}</p>
{% endfor %}

{% endblock content %}

project/templates/weekly_subscription.html
<!DOCTYPE html>
<html lang="en">
{% block content %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <p><h4>Здравствуйте! Новые статьи в твоём любимом разделе {{ name }}</h4></p>
    {% for new in posts %}
    <a href="http://127.0.0.1:8000/news/{{ new.id }}">{{ new.title }}</a><br>
    {%   endfor  %}<br>
    <br>

    <h7> С уважением, команда NewPortal</h7>
    {% endblock content %}
</body>
</html>